language: rust
rust: nightly
cache: cargo
branches:
  only:
  - master
jobs:
  include:
  - stage: build
    script:
    - cargo build --verbose
  - stage: tests
    script:
    - cargo test --verbose
  - stage: tests
    script:
    - rustup component add rustfmt-preview
    - cargo fmt -v -- --check
  - stage: tests
    script:
    - rustup component add clippy-preview
    - touch ./src/main.rs && cargo clippy -- -D warnings
notifications:
  email: false
  slack:
    secure: hPIZW1/YSFUIge4Fv5IsEt+PG+Dw6+QRB3XLFLMHSZ4C7iEYHFNxxJFu9nnrbP1naR4bObOzG22i8GK1CSGlLAeLWoN5JesoE90YkK0B05EE9fx7KI602IsXChhKSOkeZn7fuupvgEwjh2HtrZTupfWeV/URGMkJFYk8Ilw2nl8wNuo3+lunfOOpnjgbjRw+yhBnlQSt271f/wqRw/qB72cotGEf6XWrWr/KNoO4ADVEtl56n65GhEw1h5ixdiAxCNgRXnfqkyhNtDkoaflQVwfEnzhp1wiPnZ3HCvd73GXXFZs1TzAbtyyLpGqnCl2mfQW4/hzNKlEtukrH+3nJVw9lF136P0Xif43tbpfnCe88+Ug3YXu/jgVN64qszvotykoQt49ts8veSPglLfgm9XErppd+sTyds9+XNARdQQmUURUNfiLFNjjCxubo6wX8H/QUtXcQdaKCtjag7Xat23l4zwCmwujTzYbnydkSU61wQBSPFJGXDJs9xDMD28THIeqvjeRW/fpqO2WsVOr6/tCQr4rIx1XgDVfz7h5Jwmj1PKQiDRZAO/gVraGfdKVey2zcJeaD87EMWKWHcoP8umod3s+rLhIYZbQHGNT4mI2mgAjcf+n50XXKvhn1KzW1JnHEvjzH0GyiDrJ2dWgx8F8lt58tjwJpRxZIDUIdMV4=
    on_success: change
    on_failure: always
    